import { LegalPage, LegalSection } from "@/components/legal/legal-page";

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="July 20, 2026">
      <LegalSection title="The service">
        <p>
          Outrun is an AI growth platform that analyzes your business,
          identifies growth opportunities, finds and researches prospective
          customers, and generates outreach on your behalf.
        </p>
      </LegalSection>

      <LegalSection title="Your account">
        <p>
          You&apos;re responsible for the accuracy of the information you give
          Outrun and for keeping your account credentials secure.
        </p>
      </LegalSection>

      <LegalSection title="Subscriptions and billing">
        <p>
          Paid plans are billed through Paddle. You can cancel anytime from
          your Billing page; cancellation takes effect at the end of your
          current billing period.
        </p>
      </LegalSection>

      <LegalSection title="Acceptable use">
        <p>
          You agree not to use Outrun to send outreach that is deceptive,
          impersonates someone else, or violates applicable anti-spam or
          privacy laws in your jurisdiction. You&apos;re responsible for how
          you use the outreach content Outrun generates.
        </p>
      </LegalSection>

      <LegalSection title="AI-generated content">
        <p>
          Growth Blueprints, prospect research, and outreach messages are
          generated by AI based on the information available to it. Outrun
          separates observed facts from assumptions wherever possible, but
          recommendations are estimates, not guarantees — you&apos;re
          responsible for reviewing generated content before acting on or
          sending it.
        </p>
      </LegalSection>

      <LegalSection title="No guarantee of results">
        <p>
          Outrun helps you identify and act on growth opportunities. We
          don&apos;t guarantee any particular business outcome.
        </p>
      </LegalSection>

      <LegalSection title="Termination">
        <p>
          You may stop using Outrun and cancel your subscription at any time.
          We may suspend accounts that violate these terms or applicable law.
        </p>
      </LegalSection>

      <LegalSection title="Governing law">
        <p>
          These Terms are governed by the laws of South Africa, without
          regard to its conflict of law principles.
        </p>
      </LegalSection>

      <LegalSection title="Contact">
        <p>Questions about these terms: outrunv1privacy@outlook.com.</p>
      </LegalSection>
    </LegalPage>
  );
}
